### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by ZhaoQYEcho** [TBeaufils/SPIN#1]
Dear author,could you please offer your dataset used in the code？thank you every much.

**Comment by TBeaufils** [comment]
Dear Zhao,

Unfortunately, I'm not allowed to transfer the dataset used in the code, as it is licensed data.
You can access the dataset used originally at https://worldmrio.com/eora26/.
If you need an open-access dataset, you can also use Exiobase (https://www.exiobase.eu/) or the World Input-Output Database (https://www.rug.nl/ggdc/valuechain/wiod/).
