### ISSUE TITLE
where is "example_run.py"

### ISSUE THREAD

**Issue by ZhaoQYEcho** [TBeaufils/SPIN#2]
Dear author，you mentioned that "An example run is provided in code/example_run.py." But I can't find the project" code/example_run.py" Could you please tell me where it is?

Thanks!
Best Regard

**Comment by TBeaufils** [comment]
Dear Zhao,

You're right, the example file was missing.
I've synced the git with a more recent local version of the repo.
The example run is in the main page of the repo.

I had to fix some aspects of the architecture of the package. 
My apologies, this is a project that has been dormant for a while.

Best regards
